### ISSUE TITLE
Arch Linux: No such file or directory xprop

### ISSUE THREAD

**Issue by austinbutler** [dschep/ntfy#130]
In Arch after installing via pip and adding the eval to my `zshrc` I would get this:

```
Traceback (most recent call last):
  File "/usr/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/ntfy/cli.py", line 341, in main
    message, retcode = args.func(args)
  File "/usr/lib/python3.5/site-packages/ntfy/cli.py", line 64, in run_cmd
    if args.unfocused_only and is_focused():
  File "/usr/lib/python3.5/site-packages/ntfy/terminal.py", line 61, in is_focused
    return linux_window_is_focused()
  File "/usr/lib/python3.5/site-packages/ntfy/terminal.py", line 14, in linux_window_is_focused
    '_NET_ACTIVE_WINDOW']).split()[1], 16)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xprop'
```

After installing the Arch package `xorg-xprop` it works.

**Comment by dschep** [comment]
Right, I should probably document the dependency on `xprop`.

**Comment by Zaerath** [comment]
After installing xorg-xprop in Arch, I now get this:
Traceback (most recent call last):
  File "/usr/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/ntfy/cli.py", line 341, in main
    message, retcode = args.func(args)
  File "/usr/lib/python3.6/site-packages/ntfy/cli.py", line 64, in run_cmd
    if args.unfocused_only and is_focused():
  File "/usr/lib/python3.6/site-packages/ntfy/terminal.py", line 61, in is_focused
    return linux_window_is_focused()
  File "/usr/lib/python3.6/site-packages/ntfy/terminal.py", line 14, in linux_window_is_focused
    '_NET_ACTIVE_WINDOW']).split()[1], 16)
ValueError: invalid literal for int() with base 16: b'not'

Arch version:
Linux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux

**Comment by Zaerath** [comment]
Just as a quick side-note, here is my Python3 version:
$ python -V
Python 3.6.3

Utilizing --foreground-too has identical behavior.

**Comment by dschep** [comment]
Install ntfy from this git repo (`pip install -e git+https://github.com/dschep/ntfy#egg=ntfy`) to test that this has been fixed in master, I'll make a new release soon.

**Comment by Zaerath** [comment]
Wow, you are the man. I can confirm this fix works great!
