### ISSUE TITLE
ntfy[xmpp] trying to install dnspython3 with python2

### ISSUE THREAD

**Issue by rosenbergj** [dschep/ntfy#131]
**# pip install dnspython**
```
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages
```
**# pip install ntfy[xmpp]**
```
Requirement already satisfied: ntfy[xmpp] in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from ntfy[xmpp])
Requirement already satisfied: ruamel.yaml in /usr/local/lib/python2.7/dist-packages (from ntfy[xmpp])
Requirement already satisfied: appdirs in /usr/local/lib/python2.7/dist-packages (from ntfy[xmpp])
Collecting sleekxmpp; extra == "xmpp" (from ntfy[xmpp])
  Using cached sleekxmpp-1.3.1.tar.gz
Collecting dnspython3; extra == "xmpp" (from ntfy[xmpp])
  Using cached dnspython3-1.15.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5wjuwe/dnspython3/setup.py", line 25
        """+"="*78, file=sys.stdout)
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5wjuwe/dnspython3/

```

**Comment by dschep** [comment]
That's very odd, ntfy's setup.py should pick the right version: https://github.com/dschep/ntfy/blob/master/setup.py#L12

What distro are you using and are you using a virtualenv?

**Comment by rosenbergj** [comment]
Linux Mint 18, no virtualenv.

**Comment by cryoff** [comment]
I am running into the same issue.
My version of python:
> python -V
Python 2.7.12

Linux distribution:
> lsb_release -a
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

No virtualenv is used

**Comment by Piskvor** [comment]
Same issue, no virtualenv.
```
python -V
Python 2.7.13

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

```
