### ISSUE TITLE
win32 backend not reenterant

### ISSUE THREAD

**Issue by pyhedgehog** [dschep/ntfy#139]
When I'm [using](https://github.com/dschep/ntfy/issues/138) `ntfy` as a library `win32` backend produces following error:
```
ERROR:ntfy:Failed to send notification using default
Traceback (most recent call last):
  File "C:\tools\python36\lib\site-packages\ntfy\backends\default.py", line 20, in notify
    module.notify(title=title, message=message, **kwargs)
  File "C:\tools\python36\lib\site-packages\ntfy\backends\win32.py", line 54, in notify
    WindowsBalloonTip(message, title)
  File "C:\tools\python36\lib\site-packages\ntfy\backends\win32.py", line 26, in __init__
    classAtom = win32gui.RegisterClass(wc)
pywintypes.error: (1410, 'RegisterClass', 'Class already exists.')
```

**Comment by dschep** [comment]
Hmm.. That's a bummer. I'll have to fire up a windows VM sometime if I have time to debug it.

**Comment by ChrisPara** [comment]
Check this: https://stackoverflow.com/questions/33949186/error-when-trying-to-reuse-windows-notification-class-in-python
