### ISSUE TITLE
ntfy not working after reinstall

### ISSUE THREAD

**Issue by jadykes** [dschep/ntfy#151]
I reinstalled ntfy after a few commands in the quickstart routine didn't work.
During this reinstall, I upgraded pip to the most recent version (9.0.1 I think)
Now I can't get ntfy to complete even the most basic test command.
No YAML config file found.
Verbose output:
> ntfy -v send test
DEBUG: Starting new HTTPS connection (1): api.pushover.net
DEBUG: https://api.pushover.net:443 "POST /1/messages.json HTTP/1.1" 400 None
ERROR: Failed to send notification using pushover
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ntfy/__init__.py", line 56, in notify
    **backend_config)
  File "/usr/local/lib/python2.7/dist-packages/ntfy/backends/pushover.py", line 119, in notify
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: https://api.pushover.net/1/messages.json

What have I done? Since I've attempted reinstalling again and get the same result, do I need to remove and reinstall dependencies?

**Comment by dschep** [comment]
Hmm. Do you have the correct `user_key` set? I get the same error if I change mine to be wrong.
