### ISSUE TITLE
Can't send notification because of array

### ISSUE THREAD

**Issue by ryoppippi** [dschep/ntfy#167]
I try to send a notification but it doesn't work.
The error says.

```
ntfy send "test"

Traceback (most recent call last):
  File "/Users/ryoppippi/.local/share/virtualenvs/mlpractical-4EPHcjCc/bin/ntfy", line 11, in <module>
    sys.exit(main())
  File "/Users/ryoppippi/.local/share/virtualenvs/mlpractical-4EPHcjCc/lib/python3.5/site-packages/ntfy/cli.py", line 367, in main
    **dict(args.option.get(None, [])))
  File "/Users/ryoppippi/.local/share/virtualenvs/mlpractical-4EPHcjCc/lib/python3.5/site-packages/ntfy/__init__.py", line 32, in notify
    backend_config.update(kwargs)
AttributeError: 'list' object has no attribute 'update'
```

My yaml setting is here
```
backends:
  - slack
slack:
  - token: xoxp-hogehoge
  - recipient: "#general"
```

Also, this command does not work.
`ntfy -b slack -o xoxp-hogehoge "#general" send "test"`

The error message is the same above.
When I write a script using slack package from ntfy.backends, it does work.

**Comment by dschep** [comment]
Thats because your `slack` config is a list, not an object. The correct config is:
```yaml
backends:
  - slack
slack:
  token: xoxp-hogehoge
  recipient: "#general"
```

**Comment by ryoppippi** [comment]
Thank you!
It does work.

**Comment by dschep** [comment]
Glad to hear it :smiley:
