### ISSUE TITLE
Error with XMPP Backend (for Google Hangouts)

### ISSUE THREAD

**Issue by rachel-1** [dschep/ntfy#178]
When I use the XMPP backend for Google hangouts it hangs, repeatedly connecting and disconnecting. My configuration was copied from issue #25, though I couldn't use jit.si as the link was broken.
```
---
backends:
        - slack
        - xmpp
slack:
        token: "XXXXXXXXXXXXXXXXX"
        recipient: "@rachel0"
xmpp:
        jid: "XXX@gmail.com"
        password: "XXXXXXX"
        mtype: "chat"
        recipient: "XXX@gmail.com"
```
Slack works fine (though I had to use a legacy token, which wasn't documented). Note that my password for XMPP was generated via Google's application password system, and the jid and recipient are the same (my personal email). Rerunning the send command with the verbose flag (`ntfy -v send "Hi"`) yields the following:
```
DEBUG:  ==== TRANSITION connected -> disconnected
DEBUG: connecting...
DEBUG: Waiting 1.9108387935619695 seconds before connecting.
DEBUG: DNS: Querying alt4.xmpp.l.google.com for AAAA records.
DEBUG: DNS: Querying alt4.xmpp.l.google.com for A records.
DEBUG: Connecting to [2607:f8b0:400c:c14::7d]:5222
DEBUG: Event triggered: socket_error
ERROR: Could not connect to [2607:f8b0:400c:c14::7d]:5222. Socket Error #101: Network is unreachable
DEBUG: Waiting 2.0027643237949433 seconds before connecting.
DEBUG: Connecting to 173.194.218.125:5222
DEBUG: Event triggered: connected
DEBUG:  ==== TRANSITION disconnected -> connected
DEBUG: SEND (IMMED): <stream:stream to='gmail.com' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0\
'>
DEBUG: RECV: <stream:stream from="gmail.com" id="976ADDBDC250F2D7" version="1.0">
DEBUG: RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required /></starttls><me\
chanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism></mechanisms></stream:feature\
s>
DEBUG: SEND (IMMED): <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required /></starttls>
DEBUG: RECV: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls" />
DEBUG: Starting TLS
INFO: Negotiating TLS
INFO: Using SSL version: TLSv1
DEBUG: CERT: -----BEGIN CERTIFICATE-----
[long certificate]
-----END CERTIFICATE-----

DEBUG: Event triggered: ssl_cert
ERROR: Connection error.
ERROR: <TagSet object at 0x7f48070317b8 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f480704a9e8 tagSet <TagSet object at 0x7f48\
0b678e48 tags 0:0:4> encoding iso-8859-1>
Traceback (most recent call last):
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1492, in _process
    if not self.__read_xml():
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1564, in __read_xml
    self.__spawn_event(xml)
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1632, in __spawn_event
    handler.prerun(stanza_copy)
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handle_st\
arttls_proceed
    if self.xmpp.start_tls():
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 889, in start_tls
    cert.verify(self._expected_server_name, self._der_cert)
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/cert.py", line 134, in verify
    cert_names = extract_names(raw_cert)
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/sleekxmpp/xmlstream/cert.py", line 73, in extract_names
    asn1Spec=OctetString())[0]
  File "/home/paperspace/miniconda3/envs/babbl/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 1318, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: <TagSet object at 0x7f48070317b8 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f480704a9e8 tagSet <TagS\
et object at 0x7f480b678e48 tags 0:0:4> encoding iso-8859-1>
DEBUG: reconnecting...
DEBUG: Event triggered: session_end
DEBUG: SEND (IMMED): </stream:stream>
INFO: Waiting for </stream:stream> from server
DEBUG: Event triggered: disconnected
```
Any thoughts?

**Comment by dschep** [comment]
Does hangouts actually still have XMPP support?

**Comment by rachel-1** [comment]
I had looked before, but every page I found was from around 2015/2016. I had hoped it was a configuration issue on my end. After more searching it seems like it doesn't: [https://www.quora.com/Will-Google-still-support-XMPP-after-the-switch-from-Google-Talk-to-Hangouts-in-June-2017](https://www.quora.com/Will-Google-still-support-XMPP-after-the-switch-from-Google-Talk-to-Hangouts-in-June-2017). What's the main use case for the XMPP backend then? I was looking for a backend that didn't require paying anything (since I'm hoping to set up ntfy for my entire team and don't want to make people pay per user or download an app).

**Comment by dschep** [comment]
I've updated the readme to warn users that hangouts no longer supports XMPP. The use-case is any one still using XMPP based services. Not sure what those might be these days, they're still around.

For your use-case... I'm not sure. What communications tools does your team besides hangouts? In terms of comms services (as opposed to notification specific services like pushover), ntfy also supports matrix, rocketchat, slack and telegram.

As for hangouts itself, I'm sure there exists a python library that could be used to integrate hangouts support into ntfy.

**Comment by rachel-1** [comment]
They just use hangouts unfortunately...I'll think of something though. Thanks for the help!
