### ISSUE TITLE
Crashing whilst send a notification

### ISSUE THREAD

**Issue by xircon** [dschep/ntfy#221]
```
ntfy send "steve"
Traceback (most recent call last):
  File "/usr/bin/ntfy", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ntfy/cli.py", line 362, in main
    return notify(
  File "/usr/lib/python3.8/site-packages/ntfy/__init__.py", line 29, in notify
    for backend in config.get('backends', ['default']):
TypeError: 'NoneType' object is not iterable
```
Config file:
```
---
backends:
pushbullet:
    access_token: <long-access-token>
simplepush:
    key: <Key>
```
Simplepush is working, pushbullet was working but I think their server is down, any ideas?

**Comment by Cologler** [comment]
> TypeError: 'NoneType' object is not iterable

Which means the value of `backends` is empty.

So change your config to:

``` yaml
backends:
    - pushbullet             <------ then your backends set to pushbullet
pushbullet:
    access_token: <long-access-token>
simplepush:
    key: <Key>
```
