### ISSUE TITLE
SSL Exceptions when using single file binary

### ISSUE THREAD

**Issue by krohrsb** [dschep/ntfy#59]
``` bash
$ ntfy -b pushover -o user_key secret_token send 'Pushover test!'
ERROR: Failed to send notification using pushover
Traceback (most recent call last):
  File "/usr/local/bin/ntfy/ntfy/__init__.py", line 34, in notify
    module.notify(message=message, title=title, **backend_config)
  File "/usr/local/bin/ntfy/ntfy/backends/pushover.py", line 107, in notify
    headers={'User-Agent': USER_AGENT})
  File "/usr/local/bin/ntfy/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/bin/ntfy/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/bin/ntfy/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/bin/ntfy/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/bin/ntfy/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [Errno 20] Not a directory
```

Where my `secret_token` is replaced with my actual user token.

Thoughts?

**Comment by dschep** [comment]
Interesting.. how did you install ntfy? (other useful info potentially: `which ntfy` & `ntfy --version`)

**Comment by blackbarn** [comment]
I installed it similar to the readme instructions. Only difference I had to put it in /usr/local/bin due to some restrictions I have on my current system.

```
$ which ntfy & ntfy --version
[1] 57451
/usr/local/bin/ntfy
[1]  + 57451 done       which ntfy
2.0.1
```

**Comment by dschep** [comment]
Thanks, I'll check it out when I get a chance (not super easy since I don't own a mac)

**Comment by dschep** [comment]
Just got a similar report via email from a user on a RaspberyPi. Bad QA on my part, it seems to be an issue with the using requests from the single file binary. The problem presents on Linux too. I'll try get a fix ASAP. For now, please `pip install` from PyPi:
```shell
$ sudo pip install ntfy
```

**Comment by blackbarn** [comment]
Thanks! using `sudo pip install ntfy` works.

**Comment by voltagex** [comment]
https://stackoverflow.com/questions/35973137/sslerror-not-a-directory seems to be close to the problem. In theory this should happen on Windows too when using a single exe version ntfy.

**Comment by minhoryang** [comment]
same error happened
```bash
sudo /usr/bin/easy_install pip
sudo /usr/local/bin/pip psutil

git clone https://github.com/dschep/ntfy.git ntfy.git
pushd ntfy.git
bash zipapp.sh
cp dist/ntfy ~/bin/
```

```yaml
backends:
    - pushbullet
pushbullet:
    access_token: ......
```

```bash
ntfy done echo
```
